[phases.setup]
nixPkgs = [
  "python311",
  # add each dependency here, e.g.:
  # "python311Packages.flask",
  # "python311Packages.requests",
  "nodejs_20"
]

[phases.install]
cmds = [
  # no pip install here
  "cd client && npm install"
]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "cd server && gunicorn -w 4 -b 0.0.0.0:$PORT main:app"



