[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_20"]

[phases.install]
cmds = [
  # Use pip that comes with python311Packages.pip
  "pip install -r requirements.txt",
  "cd client && npm install"
]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "cd server && gunicorn -w 4 -b 0.0.0.0:$PORT main:app"
